# Generated by Django 6.0.5 on 2026-06-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_subject_school_class_transcript_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='termconfig',
            name='marks_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
