# Generated by Django 6.0.5 on 2026-06-01 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_termconfig_marks_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='classes', to='accounts.subject'),
        ),
        migrations.AlterField(
            model_name='class',
            name='series',
            field=models.CharField(blank=True, choices=[('', '---'), ('A', 'Arts (A)'), ('C', 'Science (C)'), ('D', 'Mathematics & Physics (D)'), ('TI', 'Industrial Technology (TI)'), ('A1', 'Arts A1 - Literature'), ('A2', 'Arts A2 - Bilingual Letters'), ('A3', 'Arts A3 - Philosophy'), ('A4', 'Arts A4 - Modern Letters'), ('S1', 'Science S1 - Maths/Physics'), ('S2', 'Science S2 - Life Sciences'), ('S3', 'Science S3 - Physical Sciences'), ('S4', 'Science S4 - Maths/Technology'), ('Other', 'Other')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='accounts.class'),
        ),
    ]
